barca_squad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from players import views as players_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('players/', include('players.urls')),
    path('users/', include('users.urls')),
    path('', players_views.players_list, name='home')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

players/urls.py
from django.urls import path
from . import views
app_name = 'players'
urlpatterns = [
    path('add-player/', views.add_player, name='add_player'),
    path('<slug:slug>/', views.player_details, name='details')
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

players/models.py
from django.db import models
from django.contrib.auth.models import User
import django.core.validators as validators


class Player(models.Model):
    full_name = models.CharField(max_length=60)
    short_name = models.CharField(max_length=11)
    slug = models.SlugField()
    list_pic = models.ImageField(default="")
    details_pic = models.ImageField(default="")
    birth_date = models.DateField()
    nationality = models.CharField(max_length=60)
    position = models.CharField(max_length=3, choices=[
        ('GK', 'Goalkeeper'),
        ('LB', 'Left Back'),
        ('CB', 'Center Back'),
        ('RB', 'Right Back'),
        ('CDM', 'Central Defensive Midfielder'),
        ('CM', 'Central Midfielder'),
        ('CAM', 'Central Attacking Midfielder'),
        ('LW', 'Left Winger'),
        ('ST', 'Striker'),
        ('RW', 'Right Winger')
    ])
    shirt_num = models.IntegerField(validators=[validators.MinValueValidator(1), validators.MaxValueValidator(99)],
                                    unique=True)
    facebook_link = models.URLField(max_length=100, default="", blank=True)
    instagram_link = models.URLField(max_length=100, default="", blank=True)
    twitter_link = models.URLField(max_length=100, default="", blank=True)
    bio_headline = models.CharField(max_length=200)
    player_bio = models.TextField()
    added_by = models.ForeignKey(User, default=None, limit_choices_to={'is_staff': True}, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return self.short_name


class Comment(models.Model):
    player = models.ForeignKey(Player, related_name="comments", on_delete=models.CASCADE)
    header = models.CharField(max_length=100)
    body = models.TextField(blank=True)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.posted_by} on {str(self.player)}'

users/models.py
from django.db import models

# Create your models here.

players/forms.py
from django import forms
from . import models


class AddPlayer(forms.ModelForm):
    class Meta:
        model = models.Player
        fields = ['full_name',
                  'short_name',
                  'slug',
                  'list_pic',
                  'details_pic',
                  'birth_date',
                  'nationality',
                  'position',
                  'shirt_num',
                  'facebook_link',
                  'instagram_link',
                  'twitter_link',
                  'bio_headline',
                  'player_bio'
                  ]
        widgets = {
            'birth_date': forms.SelectDateWidget(attrs={'class': 'form-select'},
                                                 years=[year for year in range(1980, 2006)]),
            'position': forms.Select(attrs={'class': 'form-select'}),
            'shirt_num': forms.TextInput(attrs={'class': 'form-control'})
        }


class AddComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['header', 'body']

        widgets = {
            'header': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'maxlength': '1000', 'rows': 6})
        }

players/views.py
from django.shortcuts import render, redirect
from .models import Player
from django.contrib.auth.decorators import login_required
from . import forms


def players_list(request):
    players = Player.objects.all().order_by('short_name')
    return render(request, 'players/players_list.html', {'players': players})


def player_details(request, slug):
    player = Player.objects.get(slug=slug)
    if request.method == 'POST':
        comment_form = forms.AddComment(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.player = player
            new_comment.posted_by = request.user
            new_comment.save()
            return redirect('players:details', slug=slug)
    else:
        comment_form = forms.AddComment()
    return render(request, 'players/player_details.html', {'player': player, 'form': comment_form})


@login_required(login_url='/users/login/')
def add_player(request):
    if request.method == 'POST':
        form = forms.AddPlayer(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.added_by = request.user
            instance.save()
            return redirect('home')
    else:
        form = forms.AddPlayer()
    return render(request, 'players/add_player.html', {'form': form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'users/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>FC Barcelona Squad</title>
    <link rel="icon" href="{% static 'pics/tab_icon.png' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/navbars/">
    <link rel="stylesheet" href="{% static 'styles/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base_layout.css' %}">
    {% block add_style %}
    {% endblock %}
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'pics/navbar-icon.png' %}"></a>
            <a class="navbar-brand" href="{% url 'home' %}">FC Barcelona Squad</a>
        <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <i class="nav-link disabled text-light ms my-auto font-italic"><strong>Hello, {{ user }}!</strong></i>
                </li>
                {% if  user.is_staff%}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'players:add_player' %}">Add Player</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <form class="logout-link" action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <a class="nav-link">
                            <button id="logout-button" type="submit">Log Out</button>
                        </a>
                    </form>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    </nav>
    <main>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <script src="{% static 'styles/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/players/add_player.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block add_style %}
    <link rel="stylesheet" href="{% static 'styles/users/add_player.css' %}">
{% endblock %}
{% block content %}
<div class="form-group mx-auto my-5 col-4 p-4 bg-dark rounded text-white">
    <form class="form-control d-grid gap-3" action="{% url 'players:add_player' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <div class = "text-center">
                <input type="submit" class="bg-secondary text-light w-50 my-1 btn btn-lg" value="Add Player">
            </div>
    </form>
</div>
{% endblock %}

templates/players/player_details.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block add_style %}
<link rel="stylesheet" href="{% static 'styles/players/details.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
{% endblock %}
{% block content %}
<div class="player-details container">
    <div class="row py-2">
        <div class="profile-widget col-10 mx-auto">
            <div class="profile-header bg-white">
                <img class="player-photo mt-2 rounded" src="{{ player.details_pic.url }}">
                <h1 class="full-name mt-2 mb-0 p-2 bg-dark text-light">{{ player.full_name }}</h1>
            </div>
            <div class="info_section bg-light p-4 d-flex justify-content-between align-items-center text-center">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item mx-2">
                        <h5 class="font-weight-bold mb-0 d-block">{{ player.shirt_num }}</h5>
                        <small class="text-muted"> <i class="fas fa-user mr-1"></i>Shirt Number</small>
                    </li>
                    <li class="list-inline-item mx-2">
                        <h5 class="font-weight-bold mb-0 d-block">{{ player.position }}</h5>
                        <small class="text-muted"> <i class="fas fa-image mr-1"></i>Position</small>
                    </li>
                    <li class="list-inline-item mx-2">
                        <h5 class="font-weight-bold mb-0 d-block">{{ player.birth_date }}</h5>
                        <small class="text-muted"> <i class="fas fa-user mr-1"></i>Date of Birth</small>
                    </li>
                    <li class="list-inline-item mx-2">
                        <h5 class="font-weight-bold mb-0 d-block">{{ player.nationality }}</h5>
                        <small class="text-muted"> <i class="fas fa-user mr-1"></i>Nationality</small>
                    </li>
                </ul>
                <ul class="list-inline mb-0">
                    {% if player.facebook_link %}
                    <a href="{{ player.facebook_link }}" target="_blank">
                        <i class="social-link bi bi-facebook p-2 mx-1" style="background: #4267B2"></i></a>
                    {% endif %}
                    {% if player.instagram_link %}
                    <a class="try" href="{{ player.instagram_link }}" target="_blank">
                        <i class="social-link bi bi-instagram p-2 mx-1" style="background: #C13584"></i></a>
                    {% endif %}
                    {% if player.twitter_link %}
                    <a href="{{ player.twitter_link }}" target="_blank">
                        <i class="social-link bi bi-twitter p-2 mx-1" style="background: #1da1f2"></i></a>
                    {% endif %}
               </ul>
            </div>
            <div class="bio-section bg-white mb-0">
                <h1 class="bio-header col-8 mx-auto pt-4">{{ player.bio_headline }}</h1>
                <p class="bio-body col-9 mx-auto my-3 py-4 text-left">{{ player.player_bio }}</p>
                <br>
            </div>
            <div class="comments-section pb-3 bg-light">
                <h1 class="ms-5 pt-3">Comments</h1>
                {% if not player.comments.all %}
                <h4 class="d-flex justify-content-around mb-5 py-4 text-secondary">No comments yet</h4>
                {% else %}
                    <ul class="comments list-group my-3">
                        {% for comment in player.comments.all %}
                        <li class="list-group-item p-2">
                            <div class="col-10 mx-auto text-left">
                                <h4 class="header ms-4 mb-0">{{ comment.header }}</h4>
                                <i class="date-added ms-4 mt-0">{{comment.date_added}}</i>
                                <p class="comment-body col-10 ms-5 mt-4">{{comment.body}}</p>
                                <b class="user-name ms-4 my-4 text-dark">By {{comment.posted_by}}</b>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            {% if user.is_authenticated %}
            <div class="add-comment form-group col-6 p-3 mt-4 bg-dark text-white mx-auto rounded">
                <form class="site-form d-grid gap-3" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" class="bg-secondary text-light w-100 mt-3 btn btn-lg" value="Add Comment">
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/players/players_list.html
{% extends 'base_layout.html' %}
{% load static %}
{% block add_style %}
<link rel="stylesheet" href="{% static 'styles/players/list.css' %}">
{% endblock %}
{% block content %}
<div class="players-list">
    {% for player in players %}
        <div class="photo-container">
            <a href="{% url 'players:details' slug=player.slug %}">
                <img class="player-photo" src="{{ player.list_pic.url }}">
            </a>
            <div class="show-player-number">
                    <div class="player-number">{{ player.shirt_num }}</div>
            </div>
            <div class="show-player-name">
                <div class="player-name">{{ player.short_name }}</div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/users/login.html
{% extends 'base_layout.html' %}
{% load crispy_forms_filters %}
{% block content %}
<div class="form-group col-3 p-3 bg-dark position-absolute top-50 start-50 translate-middle rounded">
        <form class="site-form text-white" action="{% url 'users:login' %}" method="post">
            <div class="d-grid gap-2">
                {% csrf_token %}
                {{ form | crispy }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
                {% endif %}
                <input type="submit" class="bg-secondary text-light w-100 mt-2 btn btn-lg" value="Log In">
            </div>
    </form>

</div>
{% endblock %}

templates/users/signup.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
<div class="form-group col-3 p-3 bg-dark text-white position-absolute top-50 start-50 translate-middle rounded">
        <form class="form-control bg-white d-grid gap-2" action="{% url 'users:signup' %}" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" class="form-control bg-secondary text-light w-100 my-3 btn btn-lg" value="Sign Up">
        </form>
</div>
{% endblock %}